services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput &&
                    python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis:alpine
    restart: always
    expose:
      - '6380'
    ports:
      - '6380:6380'
  celery:
    restart: always
    build: .
    command: celery -A stock_manager worker -l debug
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    build: .
    command: celery -A stock_manager beat -l debug
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - web